# Generated by Django 4.1.7 on 2023-02-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500, verbose_name='Наименование категории')),
                ('category_description', models.CharField(max_length=2000, null=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='Наименование продукта')),
                ('description', models.CharField(max_length=2000, null=True, verbose_name='Описание продукта')),
                ('added_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время добавления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('image', models.CharField(max_length=5000, null=True, verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='labwork54.category', verbose_name='Категория продукта')),
            ],
        ),
    ]
