# Generated by Django 4.1.7 on 2023-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork54', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время добавления'),
        ),
    ]
