# Generated by Django 4.1.7 on 2023-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork54', '0002_alter_product_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200000, null=True, verbose_name='Изображение'),
        ),
    ]
